# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: ift6758/serving:latest
    networks:
      - serving
    ports:
      - 5000:5000
    environment:
      COMET_API_KEY: ${COMET_API_KEY}

#### Uncomment below when you're ready to add the final notebook container to your docker compose
  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
      args:
        COMET_API_KEY: ${COMET_API_KEY}
    image: ift6758/jupyter:latest
    networks:
      - jupyter
    ports:
      - 8888:8888
    environment:
      COMET_API_KEY: ${COMET_API_KEY}
      PASSWORD: team11
networks:
  serving:
  jupyter:
    
     
